name: "Linux build"
on: push

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -yq libsdl2-dev mono-devel
      - name: Build
        run: |
          make
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: Mesen-Linux
          path: bin/x64/Release/Mesen.exe